import { Command } from 'commander';
import path from 'path';
import { generateDocumentation } from '../utils/docs-generator';

export const docsCommand = new Command('docs')
  .description('Generate documentation for MCP servers')
  .option('--dir <directory>', 'Project directory', '.')
  .option('-o, --output <directory>', 'Output directory (defaults to project directory)')
  .option('--readme', 'Generate only README.md')
  .option('--api', 'Generate only API.md')
  .option('--contributing', 'Generate only CONTRIBUTING.md')
  .option('--changelog', 'Generate only CHANGELOG.md')
  .option('--dry-run', 'Preview files without writing')
  .action(async (options) => {
    try {
      const projectPath = path.resolve(options.dir);
      const outputDir = options.output ? path.resolve(options.output) : projectPath;
      const projectName = path.basename(projectPath);

      // Determine which docs to generate
      const hasSpecificFlags = options.readme || options.api || options.contributing || options.changelog;
      const includeApi = hasSpecificFlags ? !!options.api : true;
      const includeContributing = hasSpecificFlags ? !!options.contributing : true;
      const includeChangelog = hasSpecificFlags ? !!options.changelog : true;
      const includeReadme = hasSpecificFlags ? !!options.readme : true;

      console.log(`\nGenerating documentation for ${projectName}...\n`);

      if (options.dryRun) {
        console.log('Dry run mode - files will not be written\n');
      }

      // For dry run, we'll generate but not write
      // The generateDocumentation function writes files, so we need to handle this
      if (options.dryRun) {
        console.log('Would generate:');
        if (includeReadme) console.log('  • README.md');
        if (includeApi) console.log('  • docs/API.md');
        if (includeContributing) console.log('  • CONTRIBUTING.md');
        if (includeChangelog) console.log('  • CHANGELOG.md');
        console.log('\nRun without --dry-run to generate files.\n');
        return;
      }

      const result = await generateDocumentation({
        projectPath,
        outputDir,
        includeApi,
        includeContributing,
        includeChangelog
      });

      // Filter based on readme flag (README is always generated by the function)
      const files = includeReadme
        ? result.files
        : result.files.filter(f => f.path !== 'README.md');

      console.log('Generated files:');
      for (const file of files) {
        console.log(`  ✓ ${file.path}`);
      }

      console.log('\nDocumentation generated successfully!\n');

    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      console.error(`Error: ${message}`);
      process.exit(1);
    }
  });
